import type { Plugin } from 'vite'

/**
 * Keep the server out of the browser.
 *
 * The route tree is generated by scanning `src/routes/`, and it imports every
 * file it finds — including the ones that exist only to answer a request. Both
 * builds start from that tree, so the client build follows those imports too,
 * and everything behind them comes along: Drizzle, Kysely, the Better Auth
 * server, the WebAuthn verifier, a SQLite dialect. Megabytes of code that can
 * never run in a browser, downloaded by every visitor to the panel.
 *
 * It was only ever waste until the passkey plugin arrived. Its verifier reaches
 * `@peculiar/x509`, which sets up a dependency-injection container the moment it
 * is imported and throws without `reflect-metadata` — so the panel's very first
 * chunk threw before React was reached, and `/admin` painted nothing at all.
 *
 * The fix is to say the thing that was always true: a file that answers
 * requests has nothing to give the client. In the client build each one is
 * replaced by its own declaration and no body, so the tree still has a route at
 * that path and the graph stops there. The server build is untouched.
 *
 * The marker is the file's own import of `serverRoute` — the wrapper every one
 * of them already uses to hang handlers off a route. Nothing to remember when
 * adding the next one, and nothing to keep in a list that would go stale.
 */

const ROUTE_PATH = /createFileRoute\(\s*['"]([^'"]+)['"]\s*\)/

export function serverRoutesClientStub(): Plugin {
  return {
    name: 'admincms:server-routes-client-stub',
    // Ahead of the router plugin, so what it sees is already the stub.
    enforce: 'pre',
    applyToEnvironment: (environment) => environment.name === 'client',

    transform(code, id) {
      if (!id.includes('/src/routes/')) return null
      if (!code.includes('#/lib/server-route')) return null

      const path = ROUTE_PATH.exec(code)?.[1]
      if (!path) {
        // A server route the pattern did not recognise. Left alone rather than
        // guessed at — a wrong id would break routing in a way that is much
        // harder to see than a large bundle.
        this.warn(`could not read the route path from ${id}; left in the client build`)
        return null
      }

      return {
        code: [
          `import { createFileRoute } from '@tanstack/react-router'`,
          `export const Route = createFileRoute('${path}')({})`,
          '',
        ].join('\n'),
        map: null,
      }
    },
  }
}
