/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminSplatRouteImport } from './routes/admin.$'
import { Route as AdminBuilderRouteImport } from './routes/admin.builder'
import { Route as AdminForgotRouteImport } from './routes/admin.forgot'
import { Route as AdminJoinRouteImport } from './routes/admin.join'
import { Route as AdminResetRouteImport } from './routes/admin.reset'
import { Route as ApiBillingRouteImport } from './routes/api.billing'
import { Route as ApiCheckoutRouteImport } from './routes/api.checkout'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as ApiInsightsRouteImport } from './routes/api.insights'
import { Route as ApiMcpRouteImport } from './routes/api.mcp'
import { Route as ApiPermissionsRouteImport } from './routes/api.permissions'
import { Route as ApiSettingsRouteImport } from './routes/api.settings'
import { Route as ApiUsageRouteImport } from './routes/api.usage'
import { Route as ApiVendorBillingRouteImport } from './routes/api.vendor-billing'
import { Route as ApiResourceIndexRouteImport } from './routes/api.$resource.index'
import { Route as ApiResourceIdRouteImport } from './routes/api.$resource.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'
import { Route as ApiBookHoldRouteImport } from './routes/api.book.hold'
import { Route as ApiBookServicesRouteImport } from './routes/api.book.services'
import { Route as ApiBookSlotsRouteImport } from './routes/api.book.slots'
import { Route as ApiBookingsReferenceRouteImport } from './routes/api.bookings.$reference'
import { Route as ApiBuilderCommitRouteImport } from './routes/api.builder.commit'
import { Route as ApiBuilderFileRouteImport } from './routes/api.builder.file'
import { Route as ApiCloudflareApplyRouteImport } from './routes/api.cloudflare.apply'
import { Route as ApiCloudflareAuthorizeRouteImport } from './routes/api.cloudflare.authorize'
import { Route as ApiCloudflareCallbackRouteImport } from './routes/api.cloudflare.callback'
import { Route as ApiCmsAuthRouteImport } from './routes/api.cms.auth'
import { Route as ApiCmsConfigDotymlRouteImport } from './routes/api.cms.config[.]yml'
import { Route as ApiCmsGraphqlRouteImport } from './routes/api.cms.graphql'
import { Route as ApiCmsTokenRouteImport } from './routes/api.cms.token'
import { Route as ApiDownloadTokenRouteImport } from './routes/api.download.$token'
import { Route as ApiFSlugRouteImport } from './routes/api.f.$slug'
import { Route as ApiGithubAuthorizeRouteImport } from './routes/api.github.authorize'
import { Route as ApiGithubCallbackRouteImport } from './routes/api.github.callback'
import { Route as ApiGithubSiteRouteImport } from './routes/api.github.site'
import { Route as ApiGithubStatusRouteImport } from './routes/api.github.status'
import { Route as ApiInternalProvisionRouteImport } from './routes/api.internal.provision'
import { Route as ApiInvitationsAcceptRouteImport } from './routes/api.invitations.accept'
import { Route as ApiInvitationsCreateRouteImport } from './routes/api.invitations.create'
import { Route as ApiMeDownloadsRouteImport } from './routes/api.me.downloads'
import { Route as ApiMeProfileRouteImport } from './routes/api.me.profile'
import { Route as ApiOrdersReferenceRouteImport } from './routes/api.orders.$reference'
import { Route as ApiPaymentsProviderRouteImport } from './routes/api.payments.provider'
import { Route as ApiPublicSignupRouteImport } from './routes/api.public.signup'
import { Route as ApiSettingsVerifyRouteImport } from './routes/api.settings.verify'
import { Route as ApiShopProductsRouteImport } from './routes/api.shop.products'
import { Route as ApiStaticIndexRouteImport } from './routes/api.static.index'
import { Route as ApiTeamIndexRouteImport } from './routes/api.team.index'
import { Route as ApiTeamIdRouteImport } from './routes/api.team.$id'
import { Route as ApiWebhooksGithubRouteImport } from './routes/api.webhooks.github'
import { Route as ApiWebhooksStripeRouteImport } from './routes/api.webhooks.stripe'
import { Route as ApiProductsIdAssetRouteImport } from './routes/api.products.$id.asset'
import { Route as ApiStaticCollectionIndexRouteImport } from './routes/api.static.$collection.index'
import { Route as ApiStaticCollectionIdRouteImport } from './routes/api.static.$collection.$id'
import { Route as ApiTeamIdKeysRouteImport } from './routes/api.team.$id.keys'
import { Route as ApiTeamIdPermissionsRouteImport } from './routes/api.team.$id.permissions'
import { Route as ApiVendorsIdMembersRouteImport } from './routes/api.vendors.$id.members'
import { Route as ApiVendorsIdPayoutsRouteImport } from './routes/api.vendors.$id.payouts'
import { Route as ApiCmsApiV3SplatRouteImport } from './routes/api.cms.api.v3.$'
import { Route as ApiPublicFormsSlugIndexRouteImport } from './routes/api.public.forms.$slug.index'
import { Route as ApiPublicFormsSlugSubmissionsRouteImport } from './routes/api.public.forms.$slug.submissions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSplatRoute = AdminSplatRouteImport.update({
  id: '/admin/$',
  path: '/admin/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBuilderRoute = AdminBuilderRouteImport.update({
  id: '/admin/builder',
  path: '/admin/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminForgotRoute = AdminForgotRouteImport.update({
  id: '/admin/forgot',
  path: '/admin/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminJoinRoute = AdminJoinRouteImport.update({
  id: '/admin/join',
  path: '/admin/join',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminResetRoute = AdminResetRouteImport.update({
  id: '/admin/reset',
  path: '/admin/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingRoute = ApiBillingRouteImport.update({
  id: '/api/billing',
  path: '/api/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckoutRoute = ApiCheckoutRouteImport.update({
  id: '/api/checkout',
  path: '/api/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInsightsRoute = ApiInsightsRouteImport.update({
  id: '/api/insights',
  path: '/api/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPermissionsRoute = ApiPermissionsRouteImport.update({
  id: '/api/permissions',
  path: '/api/permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSettingsRoute = ApiSettingsRouteImport.update({
  id: '/api/settings',
  path: '/api/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsageRoute = ApiUsageRouteImport.update({
  id: '/api/usage',
  path: '/api/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVendorBillingRoute = ApiVendorBillingRouteImport.update({
  id: '/api/vendor-billing',
  path: '/api/vendor-billing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResourceIndexRoute = ApiResourceIndexRouteImport.update({
  id: '/api/$resource/',
  path: '/api/$resource/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResourceIdRoute = ApiResourceIdRouteImport.update({
  id: '/api/$resource/$id',
  path: '/api/$resource/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBookHoldRoute = ApiBookHoldRouteImport.update({
  id: '/api/book/hold',
  path: '/api/book/hold',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBookServicesRoute = ApiBookServicesRouteImport.update({
  id: '/api/book/services',
  path: '/api/book/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBookSlotsRoute = ApiBookSlotsRouteImport.update({
  id: '/api/book/slots',
  path: '/api/book/slots',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBookingsReferenceRoute = ApiBookingsReferenceRouteImport.update({
  id: '/api/bookings/$reference',
  path: '/api/bookings/$reference',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBuilderCommitRoute = ApiBuilderCommitRouteImport.update({
  id: '/api/builder/commit',
  path: '/api/builder/commit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBuilderFileRoute = ApiBuilderFileRouteImport.update({
  id: '/api/builder/file',
  path: '/api/builder/file',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCloudflareApplyRoute = ApiCloudflareApplyRouteImport.update({
  id: '/api/cloudflare/apply',
  path: '/api/cloudflare/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCloudflareAuthorizeRoute = ApiCloudflareAuthorizeRouteImport.update({
  id: '/api/cloudflare/authorize',
  path: '/api/cloudflare/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCloudflareCallbackRoute = ApiCloudflareCallbackRouteImport.update({
  id: '/api/cloudflare/callback',
  path: '/api/cloudflare/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCmsAuthRoute = ApiCmsAuthRouteImport.update({
  id: '/api/cms/auth',
  path: '/api/cms/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCmsConfigDotymlRoute = ApiCmsConfigDotymlRouteImport.update({
  id: '/api/cms/config.yml',
  path: '/api/cms/config.yml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCmsGraphqlRoute = ApiCmsGraphqlRouteImport.update({
  id: '/api/cms/graphql',
  path: '/api/cms/graphql',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCmsTokenRoute = ApiCmsTokenRouteImport.update({
  id: '/api/cms/token',
  path: '/api/cms/token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDownloadTokenRoute = ApiDownloadTokenRouteImport.update({
  id: '/api/download/$token',
  path: '/api/download/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFSlugRoute = ApiFSlugRouteImport.update({
  id: '/api/f/$slug',
  path: '/api/f/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubAuthorizeRoute = ApiGithubAuthorizeRouteImport.update({
  id: '/api/github/authorize',
  path: '/api/github/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubCallbackRoute = ApiGithubCallbackRouteImport.update({
  id: '/api/github/callback',
  path: '/api/github/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubSiteRoute = ApiGithubSiteRouteImport.update({
  id: '/api/github/site',
  path: '/api/github/site',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubStatusRoute = ApiGithubStatusRouteImport.update({
  id: '/api/github/status',
  path: '/api/github/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalProvisionRoute = ApiInternalProvisionRouteImport.update({
  id: '/api/internal/provision',
  path: '/api/internal/provision',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInvitationsAcceptRoute = ApiInvitationsAcceptRouteImport.update({
  id: '/api/invitations/accept',
  path: '/api/invitations/accept',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInvitationsCreateRoute = ApiInvitationsCreateRouteImport.update({
  id: '/api/invitations/create',
  path: '/api/invitations/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeDownloadsRoute = ApiMeDownloadsRouteImport.update({
  id: '/api/me/downloads',
  path: '/api/me/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeProfileRoute = ApiMeProfileRouteImport.update({
  id: '/api/me/profile',
  path: '/api/me/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrdersReferenceRoute = ApiOrdersReferenceRouteImport.update({
  id: '/api/orders/$reference',
  path: '/api/orders/$reference',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentsProviderRoute = ApiPaymentsProviderRouteImport.update({
  id: '/api/payments/provider',
  path: '/api/payments/provider',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSignupRoute = ApiPublicSignupRouteImport.update({
  id: '/api/public/signup',
  path: '/api/public/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSettingsVerifyRoute = ApiSettingsVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => ApiSettingsRoute,
} as any)
const ApiShopProductsRoute = ApiShopProductsRouteImport.update({
  id: '/api/shop/products',
  path: '/api/shop/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStaticIndexRoute = ApiStaticIndexRouteImport.update({
  id: '/api/static/',
  path: '/api/static/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTeamIndexRoute = ApiTeamIndexRouteImport.update({
  id: '/api/team/',
  path: '/api/team/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTeamIdRoute = ApiTeamIdRouteImport.update({
  id: '/api/team/$id',
  path: '/api/team/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksGithubRoute = ApiWebhooksGithubRouteImport.update({
  id: '/api/webhooks/github',
  path: '/api/webhooks/github',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksStripeRoute = ApiWebhooksStripeRouteImport.update({
  id: '/api/webhooks/stripe',
  path: '/api/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsIdAssetRoute = ApiProductsIdAssetRouteImport.update({
  id: '/api/products/$id/asset',
  path: '/api/products/$id/asset',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStaticCollectionIndexRoute =
  ApiStaticCollectionIndexRouteImport.update({
    id: '/api/static/$collection/',
    path: '/api/static/$collection/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiStaticCollectionIdRoute = ApiStaticCollectionIdRouteImport.update({
  id: '/api/static/$collection/$id',
  path: '/api/static/$collection/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTeamIdKeysRoute = ApiTeamIdKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => ApiTeamIdRoute,
} as any)
const ApiTeamIdPermissionsRoute = ApiTeamIdPermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => ApiTeamIdRoute,
} as any)
const ApiVendorsIdMembersRoute = ApiVendorsIdMembersRouteImport.update({
  id: '/api/vendors/$id/members',
  path: '/api/vendors/$id/members',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVendorsIdPayoutsRoute = ApiVendorsIdPayoutsRouteImport.update({
  id: '/api/vendors/$id/payouts',
  path: '/api/vendors/$id/payouts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCmsApiV3SplatRoute = ApiCmsApiV3SplatRouteImport.update({
  id: '/api/cms/api/v3/$',
  path: '/api/cms/api/v3/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFormsSlugIndexRoute = ApiPublicFormsSlugIndexRouteImport.update({
  id: '/api/public/forms/$slug/',
  path: '/api/public/forms/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFormsSlugSubmissionsRoute =
  ApiPublicFormsSlugSubmissionsRouteImport.update({
    id: '/api/public/forms/$slug/submissions',
    path: '/api/public/forms/$slug/submissions',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/$': typeof AdminSplatRoute
  '/admin/builder': typeof AdminBuilderRoute
  '/admin/forgot': typeof AdminForgotRoute
  '/admin/join': typeof AdminJoinRoute
  '/admin/reset': typeof AdminResetRoute
  '/api/billing': typeof ApiBillingRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/health': typeof ApiHealthRoute
  '/api/insights': typeof ApiInsightsRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/permissions': typeof ApiPermissionsRoute
  '/api/settings': typeof ApiSettingsRouteWithChildren
  '/api/usage': typeof ApiUsageRoute
  '/api/vendor-billing': typeof ApiVendorBillingRoute
  '/admin/': typeof AdminIndexRoute
  '/api/$resource/$id': typeof ApiResourceIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/book/hold': typeof ApiBookHoldRoute
  '/api/book/services': typeof ApiBookServicesRoute
  '/api/book/slots': typeof ApiBookSlotsRoute
  '/api/bookings/$reference': typeof ApiBookingsReferenceRoute
  '/api/builder/commit': typeof ApiBuilderCommitRoute
  '/api/builder/file': typeof ApiBuilderFileRoute
  '/api/cloudflare/apply': typeof ApiCloudflareApplyRoute
  '/api/cloudflare/authorize': typeof ApiCloudflareAuthorizeRoute
  '/api/cloudflare/callback': typeof ApiCloudflareCallbackRoute
  '/api/cms/auth': typeof ApiCmsAuthRoute
  '/api/cms/config.yml': typeof ApiCmsConfigDotymlRoute
  '/api/cms/graphql': typeof ApiCmsGraphqlRoute
  '/api/cms/token': typeof ApiCmsTokenRoute
  '/api/download/$token': typeof ApiDownloadTokenRoute
  '/api/f/$slug': typeof ApiFSlugRoute
  '/api/github/authorize': typeof ApiGithubAuthorizeRoute
  '/api/github/callback': typeof ApiGithubCallbackRoute
  '/api/github/site': typeof ApiGithubSiteRoute
  '/api/github/status': typeof ApiGithubStatusRoute
  '/api/internal/provision': typeof ApiInternalProvisionRoute
  '/api/invitations/accept': typeof ApiInvitationsAcceptRoute
  '/api/invitations/create': typeof ApiInvitationsCreateRoute
  '/api/me/downloads': typeof ApiMeDownloadsRoute
  '/api/me/profile': typeof ApiMeProfileRoute
  '/api/orders/$reference': typeof ApiOrdersReferenceRoute
  '/api/payments/provider': typeof ApiPaymentsProviderRoute
  '/api/public/signup': typeof ApiPublicSignupRoute
  '/api/settings/verify': typeof ApiSettingsVerifyRoute
  '/api/shop/products': typeof ApiShopProductsRoute
  '/api/team/$id': typeof ApiTeamIdRouteWithChildren
  '/api/webhooks/github': typeof ApiWebhooksGithubRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/api/$resource/': typeof ApiResourceIndexRoute
  '/api/static/': typeof ApiStaticIndexRoute
  '/api/team/': typeof ApiTeamIndexRoute
  '/api/products/$id/asset': typeof ApiProductsIdAssetRoute
  '/api/static/$collection/$id': typeof ApiStaticCollectionIdRoute
  '/api/team/$id/keys': typeof ApiTeamIdKeysRoute
  '/api/team/$id/permissions': typeof ApiTeamIdPermissionsRoute
  '/api/vendors/$id/members': typeof ApiVendorsIdMembersRoute
  '/api/vendors/$id/payouts': typeof ApiVendorsIdPayoutsRoute
  '/api/static/$collection/': typeof ApiStaticCollectionIndexRoute
  '/api/cms/api/v3/$': typeof ApiCmsApiV3SplatRoute
  '/api/public/forms/$slug/submissions': typeof ApiPublicFormsSlugSubmissionsRoute
  '/api/public/forms/$slug/': typeof ApiPublicFormsSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/$': typeof AdminSplatRoute
  '/admin/builder': typeof AdminBuilderRoute
  '/admin/forgot': typeof AdminForgotRoute
  '/admin/join': typeof AdminJoinRoute
  '/admin/reset': typeof AdminResetRoute
  '/api/billing': typeof ApiBillingRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/health': typeof ApiHealthRoute
  '/api/insights': typeof ApiInsightsRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/permissions': typeof ApiPermissionsRoute
  '/api/settings': typeof ApiSettingsRouteWithChildren
  '/api/usage': typeof ApiUsageRoute
  '/api/vendor-billing': typeof ApiVendorBillingRoute
  '/admin': typeof AdminIndexRoute
  '/api/$resource/$id': typeof ApiResourceIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/book/hold': typeof ApiBookHoldRoute
  '/api/book/services': typeof ApiBookServicesRoute
  '/api/book/slots': typeof ApiBookSlotsRoute
  '/api/bookings/$reference': typeof ApiBookingsReferenceRoute
  '/api/builder/commit': typeof ApiBuilderCommitRoute
  '/api/builder/file': typeof ApiBuilderFileRoute
  '/api/cloudflare/apply': typeof ApiCloudflareApplyRoute
  '/api/cloudflare/authorize': typeof ApiCloudflareAuthorizeRoute
  '/api/cloudflare/callback': typeof ApiCloudflareCallbackRoute
  '/api/cms/auth': typeof ApiCmsAuthRoute
  '/api/cms/config.yml': typeof ApiCmsConfigDotymlRoute
  '/api/cms/graphql': typeof ApiCmsGraphqlRoute
  '/api/cms/token': typeof ApiCmsTokenRoute
  '/api/download/$token': typeof ApiDownloadTokenRoute
  '/api/f/$slug': typeof ApiFSlugRoute
  '/api/github/authorize': typeof ApiGithubAuthorizeRoute
  '/api/github/callback': typeof ApiGithubCallbackRoute
  '/api/github/site': typeof ApiGithubSiteRoute
  '/api/github/status': typeof ApiGithubStatusRoute
  '/api/internal/provision': typeof ApiInternalProvisionRoute
  '/api/invitations/accept': typeof ApiInvitationsAcceptRoute
  '/api/invitations/create': typeof ApiInvitationsCreateRoute
  '/api/me/downloads': typeof ApiMeDownloadsRoute
  '/api/me/profile': typeof ApiMeProfileRoute
  '/api/orders/$reference': typeof ApiOrdersReferenceRoute
  '/api/payments/provider': typeof ApiPaymentsProviderRoute
  '/api/public/signup': typeof ApiPublicSignupRoute
  '/api/settings/verify': typeof ApiSettingsVerifyRoute
  '/api/shop/products': typeof ApiShopProductsRoute
  '/api/team/$id': typeof ApiTeamIdRouteWithChildren
  '/api/webhooks/github': typeof ApiWebhooksGithubRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/api/$resource': typeof ApiResourceIndexRoute
  '/api/static': typeof ApiStaticIndexRoute
  '/api/team': typeof ApiTeamIndexRoute
  '/api/products/$id/asset': typeof ApiProductsIdAssetRoute
  '/api/static/$collection/$id': typeof ApiStaticCollectionIdRoute
  '/api/team/$id/keys': typeof ApiTeamIdKeysRoute
  '/api/team/$id/permissions': typeof ApiTeamIdPermissionsRoute
  '/api/vendors/$id/members': typeof ApiVendorsIdMembersRoute
  '/api/vendors/$id/payouts': typeof ApiVendorsIdPayoutsRoute
  '/api/static/$collection': typeof ApiStaticCollectionIndexRoute
  '/api/cms/api/v3/$': typeof ApiCmsApiV3SplatRoute
  '/api/public/forms/$slug/submissions': typeof ApiPublicFormsSlugSubmissionsRoute
  '/api/public/forms/$slug': typeof ApiPublicFormsSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/$': typeof AdminSplatRoute
  '/admin/builder': typeof AdminBuilderRoute
  '/admin/forgot': typeof AdminForgotRoute
  '/admin/join': typeof AdminJoinRoute
  '/admin/reset': typeof AdminResetRoute
  '/api/billing': typeof ApiBillingRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/health': typeof ApiHealthRoute
  '/api/insights': typeof ApiInsightsRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/permissions': typeof ApiPermissionsRoute
  '/api/settings': typeof ApiSettingsRouteWithChildren
  '/api/usage': typeof ApiUsageRoute
  '/api/vendor-billing': typeof ApiVendorBillingRoute
  '/admin/': typeof AdminIndexRoute
  '/api/$resource/$id': typeof ApiResourceIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/book/hold': typeof ApiBookHoldRoute
  '/api/book/services': typeof ApiBookServicesRoute
  '/api/book/slots': typeof ApiBookSlotsRoute
  '/api/bookings/$reference': typeof ApiBookingsReferenceRoute
  '/api/builder/commit': typeof ApiBuilderCommitRoute
  '/api/builder/file': typeof ApiBuilderFileRoute
  '/api/cloudflare/apply': typeof ApiCloudflareApplyRoute
  '/api/cloudflare/authorize': typeof ApiCloudflareAuthorizeRoute
  '/api/cloudflare/callback': typeof ApiCloudflareCallbackRoute
  '/api/cms/auth': typeof ApiCmsAuthRoute
  '/api/cms/config.yml': typeof ApiCmsConfigDotymlRoute
  '/api/cms/graphql': typeof ApiCmsGraphqlRoute
  '/api/cms/token': typeof ApiCmsTokenRoute
  '/api/download/$token': typeof ApiDownloadTokenRoute
  '/api/f/$slug': typeof ApiFSlugRoute
  '/api/github/authorize': typeof ApiGithubAuthorizeRoute
  '/api/github/callback': typeof ApiGithubCallbackRoute
  '/api/github/site': typeof ApiGithubSiteRoute
  '/api/github/status': typeof ApiGithubStatusRoute
  '/api/internal/provision': typeof ApiInternalProvisionRoute
  '/api/invitations/accept': typeof ApiInvitationsAcceptRoute
  '/api/invitations/create': typeof ApiInvitationsCreateRoute
  '/api/me/downloads': typeof ApiMeDownloadsRoute
  '/api/me/profile': typeof ApiMeProfileRoute
  '/api/orders/$reference': typeof ApiOrdersReferenceRoute
  '/api/payments/provider': typeof ApiPaymentsProviderRoute
  '/api/public/signup': typeof ApiPublicSignupRoute
  '/api/settings/verify': typeof ApiSettingsVerifyRoute
  '/api/shop/products': typeof ApiShopProductsRoute
  '/api/team/$id': typeof ApiTeamIdRouteWithChildren
  '/api/webhooks/github': typeof ApiWebhooksGithubRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/api/$resource/': typeof ApiResourceIndexRoute
  '/api/static/': typeof ApiStaticIndexRoute
  '/api/team/': typeof ApiTeamIndexRoute
  '/api/products/$id/asset': typeof ApiProductsIdAssetRoute
  '/api/static/$collection/$id': typeof ApiStaticCollectionIdRoute
  '/api/team/$id/keys': typeof ApiTeamIdKeysRoute
  '/api/team/$id/permissions': typeof ApiTeamIdPermissionsRoute
  '/api/vendors/$id/members': typeof ApiVendorsIdMembersRoute
  '/api/vendors/$id/payouts': typeof ApiVendorsIdPayoutsRoute
  '/api/static/$collection/': typeof ApiStaticCollectionIndexRoute
  '/api/cms/api/v3/$': typeof ApiCmsApiV3SplatRoute
  '/api/public/forms/$slug/submissions': typeof ApiPublicFormsSlugSubmissionsRoute
  '/api/public/forms/$slug/': typeof ApiPublicFormsSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/$'
    | '/admin/builder'
    | '/admin/forgot'
    | '/admin/join'
    | '/admin/reset'
    | '/api/billing'
    | '/api/checkout'
    | '/api/health'
    | '/api/insights'
    | '/api/mcp'
    | '/api/permissions'
    | '/api/settings'
    | '/api/usage'
    | '/api/vendor-billing'
    | '/admin/'
    | '/api/$resource/$id'
    | '/api/auth/$'
    | '/api/book/hold'
    | '/api/book/services'
    | '/api/book/slots'
    | '/api/bookings/$reference'
    | '/api/builder/commit'
    | '/api/builder/file'
    | '/api/cloudflare/apply'
    | '/api/cloudflare/authorize'
    | '/api/cloudflare/callback'
    | '/api/cms/auth'
    | '/api/cms/config.yml'
    | '/api/cms/graphql'
    | '/api/cms/token'
    | '/api/download/$token'
    | '/api/f/$slug'
    | '/api/github/authorize'
    | '/api/github/callback'
    | '/api/github/site'
    | '/api/github/status'
    | '/api/internal/provision'
    | '/api/invitations/accept'
    | '/api/invitations/create'
    | '/api/me/downloads'
    | '/api/me/profile'
    | '/api/orders/$reference'
    | '/api/payments/provider'
    | '/api/public/signup'
    | '/api/settings/verify'
    | '/api/shop/products'
    | '/api/team/$id'
    | '/api/webhooks/github'
    | '/api/webhooks/stripe'
    | '/api/$resource/'
    | '/api/static/'
    | '/api/team/'
    | '/api/products/$id/asset'
    | '/api/static/$collection/$id'
    | '/api/team/$id/keys'
    | '/api/team/$id/permissions'
    | '/api/vendors/$id/members'
    | '/api/vendors/$id/payouts'
    | '/api/static/$collection/'
    | '/api/cms/api/v3/$'
    | '/api/public/forms/$slug/submissions'
    | '/api/public/forms/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/$'
    | '/admin/builder'
    | '/admin/forgot'
    | '/admin/join'
    | '/admin/reset'
    | '/api/billing'
    | '/api/checkout'
    | '/api/health'
    | '/api/insights'
    | '/api/mcp'
    | '/api/permissions'
    | '/api/settings'
    | '/api/usage'
    | '/api/vendor-billing'
    | '/admin'
    | '/api/$resource/$id'
    | '/api/auth/$'
    | '/api/book/hold'
    | '/api/book/services'
    | '/api/book/slots'
    | '/api/bookings/$reference'
    | '/api/builder/commit'
    | '/api/builder/file'
    | '/api/cloudflare/apply'
    | '/api/cloudflare/authorize'
    | '/api/cloudflare/callback'
    | '/api/cms/auth'
    | '/api/cms/config.yml'
    | '/api/cms/graphql'
    | '/api/cms/token'
    | '/api/download/$token'
    | '/api/f/$slug'
    | '/api/github/authorize'
    | '/api/github/callback'
    | '/api/github/site'
    | '/api/github/status'
    | '/api/internal/provision'
    | '/api/invitations/accept'
    | '/api/invitations/create'
    | '/api/me/downloads'
    | '/api/me/profile'
    | '/api/orders/$reference'
    | '/api/payments/provider'
    | '/api/public/signup'
    | '/api/settings/verify'
    | '/api/shop/products'
    | '/api/team/$id'
    | '/api/webhooks/github'
    | '/api/webhooks/stripe'
    | '/api/$resource'
    | '/api/static'
    | '/api/team'
    | '/api/products/$id/asset'
    | '/api/static/$collection/$id'
    | '/api/team/$id/keys'
    | '/api/team/$id/permissions'
    | '/api/vendors/$id/members'
    | '/api/vendors/$id/payouts'
    | '/api/static/$collection'
    | '/api/cms/api/v3/$'
    | '/api/public/forms/$slug/submissions'
    | '/api/public/forms/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin/$'
    | '/admin/builder'
    | '/admin/forgot'
    | '/admin/join'
    | '/admin/reset'
    | '/api/billing'
    | '/api/checkout'
    | '/api/health'
    | '/api/insights'
    | '/api/mcp'
    | '/api/permissions'
    | '/api/settings'
    | '/api/usage'
    | '/api/vendor-billing'
    | '/admin/'
    | '/api/$resource/$id'
    | '/api/auth/$'
    | '/api/book/hold'
    | '/api/book/services'
    | '/api/book/slots'
    | '/api/bookings/$reference'
    | '/api/builder/commit'
    | '/api/builder/file'
    | '/api/cloudflare/apply'
    | '/api/cloudflare/authorize'
    | '/api/cloudflare/callback'
    | '/api/cms/auth'
    | '/api/cms/config.yml'
    | '/api/cms/graphql'
    | '/api/cms/token'
    | '/api/download/$token'
    | '/api/f/$slug'
    | '/api/github/authorize'
    | '/api/github/callback'
    | '/api/github/site'
    | '/api/github/status'
    | '/api/internal/provision'
    | '/api/invitations/accept'
    | '/api/invitations/create'
    | '/api/me/downloads'
    | '/api/me/profile'
    | '/api/orders/$reference'
    | '/api/payments/provider'
    | '/api/public/signup'
    | '/api/settings/verify'
    | '/api/shop/products'
    | '/api/team/$id'
    | '/api/webhooks/github'
    | '/api/webhooks/stripe'
    | '/api/$resource/'
    | '/api/static/'
    | '/api/team/'
    | '/api/products/$id/asset'
    | '/api/static/$collection/$id'
    | '/api/team/$id/keys'
    | '/api/team/$id/permissions'
    | '/api/vendors/$id/members'
    | '/api/vendors/$id/payouts'
    | '/api/static/$collection/'
    | '/api/cms/api/v3/$'
    | '/api/public/forms/$slug/submissions'
    | '/api/public/forms/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminSplatRoute: typeof AdminSplatRoute
  AdminBuilderRoute: typeof AdminBuilderRoute
  AdminForgotRoute: typeof AdminForgotRoute
  AdminJoinRoute: typeof AdminJoinRoute
  AdminResetRoute: typeof AdminResetRoute
  ApiBillingRoute: typeof ApiBillingRoute
  ApiCheckoutRoute: typeof ApiCheckoutRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiInsightsRoute: typeof ApiInsightsRoute
  ApiMcpRoute: typeof ApiMcpRoute
  ApiPermissionsRoute: typeof ApiPermissionsRoute
  ApiSettingsRoute: typeof ApiSettingsRouteWithChildren
  ApiUsageRoute: typeof ApiUsageRoute
  ApiVendorBillingRoute: typeof ApiVendorBillingRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ApiResourceIdRoute: typeof ApiResourceIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiBookHoldRoute: typeof ApiBookHoldRoute
  ApiBookServicesRoute: typeof ApiBookServicesRoute
  ApiBookSlotsRoute: typeof ApiBookSlotsRoute
  ApiBookingsReferenceRoute: typeof ApiBookingsReferenceRoute
  ApiBuilderCommitRoute: typeof ApiBuilderCommitRoute
  ApiBuilderFileRoute: typeof ApiBuilderFileRoute
  ApiCloudflareApplyRoute: typeof ApiCloudflareApplyRoute
  ApiCloudflareAuthorizeRoute: typeof ApiCloudflareAuthorizeRoute
  ApiCloudflareCallbackRoute: typeof ApiCloudflareCallbackRoute
  ApiCmsAuthRoute: typeof ApiCmsAuthRoute
  ApiCmsConfigDotymlRoute: typeof ApiCmsConfigDotymlRoute
  ApiCmsGraphqlRoute: typeof ApiCmsGraphqlRoute
  ApiCmsTokenRoute: typeof ApiCmsTokenRoute
  ApiDownloadTokenRoute: typeof ApiDownloadTokenRoute
  ApiFSlugRoute: typeof ApiFSlugRoute
  ApiGithubAuthorizeRoute: typeof ApiGithubAuthorizeRoute
  ApiGithubCallbackRoute: typeof ApiGithubCallbackRoute
  ApiGithubSiteRoute: typeof ApiGithubSiteRoute
  ApiGithubStatusRoute: typeof ApiGithubStatusRoute
  ApiInternalProvisionRoute: typeof ApiInternalProvisionRoute
  ApiInvitationsAcceptRoute: typeof ApiInvitationsAcceptRoute
  ApiInvitationsCreateRoute: typeof ApiInvitationsCreateRoute
  ApiMeDownloadsRoute: typeof ApiMeDownloadsRoute
  ApiMeProfileRoute: typeof ApiMeProfileRoute
  ApiOrdersReferenceRoute: typeof ApiOrdersReferenceRoute
  ApiPaymentsProviderRoute: typeof ApiPaymentsProviderRoute
  ApiPublicSignupRoute: typeof ApiPublicSignupRoute
  ApiShopProductsRoute: typeof ApiShopProductsRoute
  ApiTeamIdRoute: typeof ApiTeamIdRouteWithChildren
  ApiWebhooksGithubRoute: typeof ApiWebhooksGithubRoute
  ApiWebhooksStripeRoute: typeof ApiWebhooksStripeRoute
  ApiResourceIndexRoute: typeof ApiResourceIndexRoute
  ApiStaticIndexRoute: typeof ApiStaticIndexRoute
  ApiTeamIndexRoute: typeof ApiTeamIndexRoute
  ApiProductsIdAssetRoute: typeof ApiProductsIdAssetRoute
  ApiStaticCollectionIdRoute: typeof ApiStaticCollectionIdRoute
  ApiVendorsIdMembersRoute: typeof ApiVendorsIdMembersRoute
  ApiVendorsIdPayoutsRoute: typeof ApiVendorsIdPayoutsRoute
  ApiStaticCollectionIndexRoute: typeof ApiStaticCollectionIndexRoute
  ApiCmsApiV3SplatRoute: typeof ApiCmsApiV3SplatRoute
  ApiPublicFormsSlugSubmissionsRoute: typeof ApiPublicFormsSlugSubmissionsRoute
  ApiPublicFormsSlugIndexRoute: typeof ApiPublicFormsSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$': {
      id: '/admin/$'
      path: '/admin/$'
      fullPath: '/admin/$'
      preLoaderRoute: typeof AdminSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/builder': {
      id: '/admin/builder'
      path: '/admin/builder'
      fullPath: '/admin/builder'
      preLoaderRoute: typeof AdminBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/forgot': {
      id: '/admin/forgot'
      path: '/admin/forgot'
      fullPath: '/admin/forgot'
      preLoaderRoute: typeof AdminForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/join': {
      id: '/admin/join'
      path: '/admin/join'
      fullPath: '/admin/join'
      preLoaderRoute: typeof AdminJoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reset': {
      id: '/admin/reset'
      path: '/admin/reset'
      fullPath: '/admin/reset'
      preLoaderRoute: typeof AdminResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing': {
      id: '/api/billing'
      path: '/api/billing'
      fullPath: '/api/billing'
      preLoaderRoute: typeof ApiBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkout': {
      id: '/api/checkout'
      path: '/api/checkout'
      fullPath: '/api/checkout'
      preLoaderRoute: typeof ApiCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/insights': {
      id: '/api/insights'
      path: '/api/insights'
      fullPath: '/api/insights'
      preLoaderRoute: typeof ApiInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/permissions': {
      id: '/api/permissions'
      path: '/api/permissions'
      fullPath: '/api/permissions'
      preLoaderRoute: typeof ApiPermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/settings': {
      id: '/api/settings'
      path: '/api/settings'
      fullPath: '/api/settings'
      preLoaderRoute: typeof ApiSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/usage': {
      id: '/api/usage'
      path: '/api/usage'
      fullPath: '/api/usage'
      preLoaderRoute: typeof ApiUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vendor-billing': {
      id: '/api/vendor-billing'
      path: '/api/vendor-billing'
      fullPath: '/api/vendor-billing'
      preLoaderRoute: typeof ApiVendorBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$resource/': {
      id: '/api/$resource/'
      path: '/api/$resource'
      fullPath: '/api/$resource/'
      preLoaderRoute: typeof ApiResourceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$resource/$id': {
      id: '/api/$resource/$id'
      path: '/api/$resource/$id'
      fullPath: '/api/$resource/$id'
      preLoaderRoute: typeof ApiResourceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/book/hold': {
      id: '/api/book/hold'
      path: '/api/book/hold'
      fullPath: '/api/book/hold'
      preLoaderRoute: typeof ApiBookHoldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/book/services': {
      id: '/api/book/services'
      path: '/api/book/services'
      fullPath: '/api/book/services'
      preLoaderRoute: typeof ApiBookServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/book/slots': {
      id: '/api/book/slots'
      path: '/api/book/slots'
      fullPath: '/api/book/slots'
      preLoaderRoute: typeof ApiBookSlotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bookings/$reference': {
      id: '/api/bookings/$reference'
      path: '/api/bookings/$reference'
      fullPath: '/api/bookings/$reference'
      preLoaderRoute: typeof ApiBookingsReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/builder/commit': {
      id: '/api/builder/commit'
      path: '/api/builder/commit'
      fullPath: '/api/builder/commit'
      preLoaderRoute: typeof ApiBuilderCommitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/builder/file': {
      id: '/api/builder/file'
      path: '/api/builder/file'
      fullPath: '/api/builder/file'
      preLoaderRoute: typeof ApiBuilderFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cloudflare/apply': {
      id: '/api/cloudflare/apply'
      path: '/api/cloudflare/apply'
      fullPath: '/api/cloudflare/apply'
      preLoaderRoute: typeof ApiCloudflareApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cloudflare/authorize': {
      id: '/api/cloudflare/authorize'
      path: '/api/cloudflare/authorize'
      fullPath: '/api/cloudflare/authorize'
      preLoaderRoute: typeof ApiCloudflareAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cloudflare/callback': {
      id: '/api/cloudflare/callback'
      path: '/api/cloudflare/callback'
      fullPath: '/api/cloudflare/callback'
      preLoaderRoute: typeof ApiCloudflareCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cms/auth': {
      id: '/api/cms/auth'
      path: '/api/cms/auth'
      fullPath: '/api/cms/auth'
      preLoaderRoute: typeof ApiCmsAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cms/config.yml': {
      id: '/api/cms/config.yml'
      path: '/api/cms/config.yml'
      fullPath: '/api/cms/config.yml'
      preLoaderRoute: typeof ApiCmsConfigDotymlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cms/graphql': {
      id: '/api/cms/graphql'
      path: '/api/cms/graphql'
      fullPath: '/api/cms/graphql'
      preLoaderRoute: typeof ApiCmsGraphqlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cms/token': {
      id: '/api/cms/token'
      path: '/api/cms/token'
      fullPath: '/api/cms/token'
      preLoaderRoute: typeof ApiCmsTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/download/$token': {
      id: '/api/download/$token'
      path: '/api/download/$token'
      fullPath: '/api/download/$token'
      preLoaderRoute: typeof ApiDownloadTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/f/$slug': {
      id: '/api/f/$slug'
      path: '/api/f/$slug'
      fullPath: '/api/f/$slug'
      preLoaderRoute: typeof ApiFSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/authorize': {
      id: '/api/github/authorize'
      path: '/api/github/authorize'
      fullPath: '/api/github/authorize'
      preLoaderRoute: typeof ApiGithubAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/callback': {
      id: '/api/github/callback'
      path: '/api/github/callback'
      fullPath: '/api/github/callback'
      preLoaderRoute: typeof ApiGithubCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/site': {
      id: '/api/github/site'
      path: '/api/github/site'
      fullPath: '/api/github/site'
      preLoaderRoute: typeof ApiGithubSiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/status': {
      id: '/api/github/status'
      path: '/api/github/status'
      fullPath: '/api/github/status'
      preLoaderRoute: typeof ApiGithubStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/provision': {
      id: '/api/internal/provision'
      path: '/api/internal/provision'
      fullPath: '/api/internal/provision'
      preLoaderRoute: typeof ApiInternalProvisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/invitations/accept': {
      id: '/api/invitations/accept'
      path: '/api/invitations/accept'
      fullPath: '/api/invitations/accept'
      preLoaderRoute: typeof ApiInvitationsAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/invitations/create': {
      id: '/api/invitations/create'
      path: '/api/invitations/create'
      fullPath: '/api/invitations/create'
      preLoaderRoute: typeof ApiInvitationsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me/downloads': {
      id: '/api/me/downloads'
      path: '/api/me/downloads'
      fullPath: '/api/me/downloads'
      preLoaderRoute: typeof ApiMeDownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me/profile': {
      id: '/api/me/profile'
      path: '/api/me/profile'
      fullPath: '/api/me/profile'
      preLoaderRoute: typeof ApiMeProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orders/$reference': {
      id: '/api/orders/$reference'
      path: '/api/orders/$reference'
      fullPath: '/api/orders/$reference'
      preLoaderRoute: typeof ApiOrdersReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/provider': {
      id: '/api/payments/provider'
      path: '/api/payments/provider'
      fullPath: '/api/payments/provider'
      preLoaderRoute: typeof ApiPaymentsProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/signup': {
      id: '/api/public/signup'
      path: '/api/public/signup'
      fullPath: '/api/public/signup'
      preLoaderRoute: typeof ApiPublicSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/settings/verify': {
      id: '/api/settings/verify'
      path: '/verify'
      fullPath: '/api/settings/verify'
      preLoaderRoute: typeof ApiSettingsVerifyRouteImport
      parentRoute: typeof ApiSettingsRoute
    }
    '/api/shop/products': {
      id: '/api/shop/products'
      path: '/api/shop/products'
      fullPath: '/api/shop/products'
      preLoaderRoute: typeof ApiShopProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/static/': {
      id: '/api/static/'
      path: '/api/static'
      fullPath: '/api/static/'
      preLoaderRoute: typeof ApiStaticIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/team/': {
      id: '/api/team/'
      path: '/api/team'
      fullPath: '/api/team/'
      preLoaderRoute: typeof ApiTeamIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/team/$id': {
      id: '/api/team/$id'
      path: '/api/team/$id'
      fullPath: '/api/team/$id'
      preLoaderRoute: typeof ApiTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/github': {
      id: '/api/webhooks/github'
      path: '/api/webhooks/github'
      fullPath: '/api/webhooks/github'
      preLoaderRoute: typeof ApiWebhooksGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/stripe': {
      id: '/api/webhooks/stripe'
      path: '/api/webhooks/stripe'
      fullPath: '/api/webhooks/stripe'
      preLoaderRoute: typeof ApiWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/$id/asset': {
      id: '/api/products/$id/asset'
      path: '/api/products/$id/asset'
      fullPath: '/api/products/$id/asset'
      preLoaderRoute: typeof ApiProductsIdAssetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/static/$collection/': {
      id: '/api/static/$collection/'
      path: '/api/static/$collection'
      fullPath: '/api/static/$collection/'
      preLoaderRoute: typeof ApiStaticCollectionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/static/$collection/$id': {
      id: '/api/static/$collection/$id'
      path: '/api/static/$collection/$id'
      fullPath: '/api/static/$collection/$id'
      preLoaderRoute: typeof ApiStaticCollectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/team/$id/keys': {
      id: '/api/team/$id/keys'
      path: '/keys'
      fullPath: '/api/team/$id/keys'
      preLoaderRoute: typeof ApiTeamIdKeysRouteImport
      parentRoute: typeof ApiTeamIdRoute
    }
    '/api/team/$id/permissions': {
      id: '/api/team/$id/permissions'
      path: '/permissions'
      fullPath: '/api/team/$id/permissions'
      preLoaderRoute: typeof ApiTeamIdPermissionsRouteImport
      parentRoute: typeof ApiTeamIdRoute
    }
    '/api/vendors/$id/members': {
      id: '/api/vendors/$id/members'
      path: '/api/vendors/$id/members'
      fullPath: '/api/vendors/$id/members'
      preLoaderRoute: typeof ApiVendorsIdMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vendors/$id/payouts': {
      id: '/api/vendors/$id/payouts'
      path: '/api/vendors/$id/payouts'
      fullPath: '/api/vendors/$id/payouts'
      preLoaderRoute: typeof ApiVendorsIdPayoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cms/api/v3/$': {
      id: '/api/cms/api/v3/$'
      path: '/api/cms/api/v3/$'
      fullPath: '/api/cms/api/v3/$'
      preLoaderRoute: typeof ApiCmsApiV3SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/forms/$slug/': {
      id: '/api/public/forms/$slug/'
      path: '/api/public/forms/$slug'
      fullPath: '/api/public/forms/$slug/'
      preLoaderRoute: typeof ApiPublicFormsSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/forms/$slug/submissions': {
      id: '/api/public/forms/$slug/submissions'
      path: '/api/public/forms/$slug/submissions'
      fullPath: '/api/public/forms/$slug/submissions'
      preLoaderRoute: typeof ApiPublicFormsSlugSubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiSettingsRouteChildren {
  ApiSettingsVerifyRoute: typeof ApiSettingsVerifyRoute
}

const ApiSettingsRouteChildren: ApiSettingsRouteChildren = {
  ApiSettingsVerifyRoute: ApiSettingsVerifyRoute,
}

const ApiSettingsRouteWithChildren = ApiSettingsRoute._addFileChildren(
  ApiSettingsRouteChildren,
)

interface ApiTeamIdRouteChildren {
  ApiTeamIdKeysRoute: typeof ApiTeamIdKeysRoute
  ApiTeamIdPermissionsRoute: typeof ApiTeamIdPermissionsRoute
}

const ApiTeamIdRouteChildren: ApiTeamIdRouteChildren = {
  ApiTeamIdKeysRoute: ApiTeamIdKeysRoute,
  ApiTeamIdPermissionsRoute: ApiTeamIdPermissionsRoute,
}

const ApiTeamIdRouteWithChildren = ApiTeamIdRoute._addFileChildren(
  ApiTeamIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminSplatRoute: AdminSplatRoute,
  AdminBuilderRoute: AdminBuilderRoute,
  AdminForgotRoute: AdminForgotRoute,
  AdminJoinRoute: AdminJoinRoute,
  AdminResetRoute: AdminResetRoute,
  ApiBillingRoute: ApiBillingRoute,
  ApiCheckoutRoute: ApiCheckoutRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiInsightsRoute: ApiInsightsRoute,
  ApiMcpRoute: ApiMcpRoute,
  ApiPermissionsRoute: ApiPermissionsRoute,
  ApiSettingsRoute: ApiSettingsRouteWithChildren,
  ApiUsageRoute: ApiUsageRoute,
  ApiVendorBillingRoute: ApiVendorBillingRoute,
  AdminIndexRoute: AdminIndexRoute,
  ApiResourceIdRoute: ApiResourceIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiBookHoldRoute: ApiBookHoldRoute,
  ApiBookServicesRoute: ApiBookServicesRoute,
  ApiBookSlotsRoute: ApiBookSlotsRoute,
  ApiBookingsReferenceRoute: ApiBookingsReferenceRoute,
  ApiBuilderCommitRoute: ApiBuilderCommitRoute,
  ApiBuilderFileRoute: ApiBuilderFileRoute,
  ApiCloudflareApplyRoute: ApiCloudflareApplyRoute,
  ApiCloudflareAuthorizeRoute: ApiCloudflareAuthorizeRoute,
  ApiCloudflareCallbackRoute: ApiCloudflareCallbackRoute,
  ApiCmsAuthRoute: ApiCmsAuthRoute,
  ApiCmsConfigDotymlRoute: ApiCmsConfigDotymlRoute,
  ApiCmsGraphqlRoute: ApiCmsGraphqlRoute,
  ApiCmsTokenRoute: ApiCmsTokenRoute,
  ApiDownloadTokenRoute: ApiDownloadTokenRoute,
  ApiFSlugRoute: ApiFSlugRoute,
  ApiGithubAuthorizeRoute: ApiGithubAuthorizeRoute,
  ApiGithubCallbackRoute: ApiGithubCallbackRoute,
  ApiGithubSiteRoute: ApiGithubSiteRoute,
  ApiGithubStatusRoute: ApiGithubStatusRoute,
  ApiInternalProvisionRoute: ApiInternalProvisionRoute,
  ApiInvitationsAcceptRoute: ApiInvitationsAcceptRoute,
  ApiInvitationsCreateRoute: ApiInvitationsCreateRoute,
  ApiMeDownloadsRoute: ApiMeDownloadsRoute,
  ApiMeProfileRoute: ApiMeProfileRoute,
  ApiOrdersReferenceRoute: ApiOrdersReferenceRoute,
  ApiPaymentsProviderRoute: ApiPaymentsProviderRoute,
  ApiPublicSignupRoute: ApiPublicSignupRoute,
  ApiShopProductsRoute: ApiShopProductsRoute,
  ApiTeamIdRoute: ApiTeamIdRouteWithChildren,
  ApiWebhooksGithubRoute: ApiWebhooksGithubRoute,
  ApiWebhooksStripeRoute: ApiWebhooksStripeRoute,
  ApiResourceIndexRoute: ApiResourceIndexRoute,
  ApiStaticIndexRoute: ApiStaticIndexRoute,
  ApiTeamIndexRoute: ApiTeamIndexRoute,
  ApiProductsIdAssetRoute: ApiProductsIdAssetRoute,
  ApiStaticCollectionIdRoute: ApiStaticCollectionIdRoute,
  ApiVendorsIdMembersRoute: ApiVendorsIdMembersRoute,
  ApiVendorsIdPayoutsRoute: ApiVendorsIdPayoutsRoute,
  ApiStaticCollectionIndexRoute: ApiStaticCollectionIndexRoute,
  ApiCmsApiV3SplatRoute: ApiCmsApiV3SplatRoute,
  ApiPublicFormsSlugSubmissionsRoute: ApiPublicFormsSlugSubmissionsRoute,
  ApiPublicFormsSlugIndexRoute: ApiPublicFormsSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
