/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminSplatRouteImport } from './routes/admin.$'
import { Route as AdminBuilderRouteImport } from './routes/admin.builder'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as ApiSettingsRouteImport } from './routes/api.settings'
import { Route as ApiResourceIndexRouteImport } from './routes/api.$resource.index'
import { Route as ApiResourceIdRouteImport } from './routes/api.$resource.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'
import { Route as ApiBuilderCommitRouteImport } from './routes/api.builder.commit'
import { Route as ApiBuilderFileRouteImport } from './routes/api.builder.file'
import { Route as ApiCloudflareApplyRouteImport } from './routes/api.cloudflare.apply'
import { Route as ApiCloudflareAuthorizeRouteImport } from './routes/api.cloudflare.authorize'
import { Route as ApiCloudflareCallbackRouteImport } from './routes/api.cloudflare.callback'
import { Route as ApiFSlugRouteImport } from './routes/api.f.$slug'
import { Route as ApiGithubAuthorizeRouteImport } from './routes/api.github.authorize'
import { Route as ApiGithubCallbackRouteImport } from './routes/api.github.callback'
import { Route as ApiGithubSiteRouteImport } from './routes/api.github.site'
import { Route as ApiGithubStatusRouteImport } from './routes/api.github.status'
import { Route as ApiInternalProvisionRouteImport } from './routes/api.internal.provision'
import { Route as ApiSettingsVerifyRouteImport } from './routes/api.settings.verify'
import { Route as ApiStaticIndexRouteImport } from './routes/api.static.index'
import { Route as ApiStaticCollectionIndexRouteImport } from './routes/api.static.$collection.index'
import { Route as ApiStaticCollectionIdRouteImport } from './routes/api.static.$collection.$id'
import { Route as ApiPublicFormsSlugIndexRouteImport } from './routes/api.public.forms.$slug.index'
import { Route as ApiPublicFormsSlugSubmissionsRouteImport } from './routes/api.public.forms.$slug.submissions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSplatRoute = AdminSplatRouteImport.update({
  id: '/admin/$',
  path: '/admin/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBuilderRoute = AdminBuilderRouteImport.update({
  id: '/admin/builder',
  path: '/admin/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSettingsRoute = ApiSettingsRouteImport.update({
  id: '/api/settings',
  path: '/api/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResourceIndexRoute = ApiResourceIndexRouteImport.update({
  id: '/api/$resource/',
  path: '/api/$resource/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResourceIdRoute = ApiResourceIdRouteImport.update({
  id: '/api/$resource/$id',
  path: '/api/$resource/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBuilderCommitRoute = ApiBuilderCommitRouteImport.update({
  id: '/api/builder/commit',
  path: '/api/builder/commit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBuilderFileRoute = ApiBuilderFileRouteImport.update({
  id: '/api/builder/file',
  path: '/api/builder/file',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCloudflareApplyRoute = ApiCloudflareApplyRouteImport.update({
  id: '/api/cloudflare/apply',
  path: '/api/cloudflare/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCloudflareAuthorizeRoute = ApiCloudflareAuthorizeRouteImport.update({
  id: '/api/cloudflare/authorize',
  path: '/api/cloudflare/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCloudflareCallbackRoute = ApiCloudflareCallbackRouteImport.update({
  id: '/api/cloudflare/callback',
  path: '/api/cloudflare/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFSlugRoute = ApiFSlugRouteImport.update({
  id: '/api/f/$slug',
  path: '/api/f/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubAuthorizeRoute = ApiGithubAuthorizeRouteImport.update({
  id: '/api/github/authorize',
  path: '/api/github/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubCallbackRoute = ApiGithubCallbackRouteImport.update({
  id: '/api/github/callback',
  path: '/api/github/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubSiteRoute = ApiGithubSiteRouteImport.update({
  id: '/api/github/site',
  path: '/api/github/site',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubStatusRoute = ApiGithubStatusRouteImport.update({
  id: '/api/github/status',
  path: '/api/github/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalProvisionRoute = ApiInternalProvisionRouteImport.update({
  id: '/api/internal/provision',
  path: '/api/internal/provision',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSettingsVerifyRoute = ApiSettingsVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => ApiSettingsRoute,
} as any)
const ApiStaticIndexRoute = ApiStaticIndexRouteImport.update({
  id: '/api/static/',
  path: '/api/static/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStaticCollectionIndexRoute =
  ApiStaticCollectionIndexRouteImport.update({
    id: '/api/static/$collection/',
    path: '/api/static/$collection/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiStaticCollectionIdRoute = ApiStaticCollectionIdRouteImport.update({
  id: '/api/static/$collection/$id',
  path: '/api/static/$collection/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFormsSlugIndexRoute = ApiPublicFormsSlugIndexRouteImport.update({
  id: '/api/public/forms/$slug/',
  path: '/api/public/forms/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFormsSlugSubmissionsRoute =
  ApiPublicFormsSlugSubmissionsRouteImport.update({
    id: '/api/public/forms/$slug/submissions',
    path: '/api/public/forms/$slug/submissions',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/$': typeof AdminSplatRoute
  '/admin/builder': typeof AdminBuilderRoute
  '/api/health': typeof ApiHealthRoute
  '/api/settings': typeof ApiSettingsRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/api/$resource/$id': typeof ApiResourceIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/builder/commit': typeof ApiBuilderCommitRoute
  '/api/builder/file': typeof ApiBuilderFileRoute
  '/api/cloudflare/apply': typeof ApiCloudflareApplyRoute
  '/api/cloudflare/authorize': typeof ApiCloudflareAuthorizeRoute
  '/api/cloudflare/callback': typeof ApiCloudflareCallbackRoute
  '/api/f/$slug': typeof ApiFSlugRoute
  '/api/github/authorize': typeof ApiGithubAuthorizeRoute
  '/api/github/callback': typeof ApiGithubCallbackRoute
  '/api/github/site': typeof ApiGithubSiteRoute
  '/api/github/status': typeof ApiGithubStatusRoute
  '/api/internal/provision': typeof ApiInternalProvisionRoute
  '/api/settings/verify': typeof ApiSettingsVerifyRoute
  '/api/$resource/': typeof ApiResourceIndexRoute
  '/api/static/': typeof ApiStaticIndexRoute
  '/api/static/$collection/$id': typeof ApiStaticCollectionIdRoute
  '/api/static/$collection/': typeof ApiStaticCollectionIndexRoute
  '/api/public/forms/$slug/submissions': typeof ApiPublicFormsSlugSubmissionsRoute
  '/api/public/forms/$slug/': typeof ApiPublicFormsSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/$': typeof AdminSplatRoute
  '/admin/builder': typeof AdminBuilderRoute
  '/api/health': typeof ApiHealthRoute
  '/api/settings': typeof ApiSettingsRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/api/$resource/$id': typeof ApiResourceIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/builder/commit': typeof ApiBuilderCommitRoute
  '/api/builder/file': typeof ApiBuilderFileRoute
  '/api/cloudflare/apply': typeof ApiCloudflareApplyRoute
  '/api/cloudflare/authorize': typeof ApiCloudflareAuthorizeRoute
  '/api/cloudflare/callback': typeof ApiCloudflareCallbackRoute
  '/api/f/$slug': typeof ApiFSlugRoute
  '/api/github/authorize': typeof ApiGithubAuthorizeRoute
  '/api/github/callback': typeof ApiGithubCallbackRoute
  '/api/github/site': typeof ApiGithubSiteRoute
  '/api/github/status': typeof ApiGithubStatusRoute
  '/api/internal/provision': typeof ApiInternalProvisionRoute
  '/api/settings/verify': typeof ApiSettingsVerifyRoute
  '/api/$resource': typeof ApiResourceIndexRoute
  '/api/static': typeof ApiStaticIndexRoute
  '/api/static/$collection/$id': typeof ApiStaticCollectionIdRoute
  '/api/static/$collection': typeof ApiStaticCollectionIndexRoute
  '/api/public/forms/$slug/submissions': typeof ApiPublicFormsSlugSubmissionsRoute
  '/api/public/forms/$slug': typeof ApiPublicFormsSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/$': typeof AdminSplatRoute
  '/admin/builder': typeof AdminBuilderRoute
  '/api/health': typeof ApiHealthRoute
  '/api/settings': typeof ApiSettingsRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/api/$resource/$id': typeof ApiResourceIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/builder/commit': typeof ApiBuilderCommitRoute
  '/api/builder/file': typeof ApiBuilderFileRoute
  '/api/cloudflare/apply': typeof ApiCloudflareApplyRoute
  '/api/cloudflare/authorize': typeof ApiCloudflareAuthorizeRoute
  '/api/cloudflare/callback': typeof ApiCloudflareCallbackRoute
  '/api/f/$slug': typeof ApiFSlugRoute
  '/api/github/authorize': typeof ApiGithubAuthorizeRoute
  '/api/github/callback': typeof ApiGithubCallbackRoute
  '/api/github/site': typeof ApiGithubSiteRoute
  '/api/github/status': typeof ApiGithubStatusRoute
  '/api/internal/provision': typeof ApiInternalProvisionRoute
  '/api/settings/verify': typeof ApiSettingsVerifyRoute
  '/api/$resource/': typeof ApiResourceIndexRoute
  '/api/static/': typeof ApiStaticIndexRoute
  '/api/static/$collection/$id': typeof ApiStaticCollectionIdRoute
  '/api/static/$collection/': typeof ApiStaticCollectionIndexRoute
  '/api/public/forms/$slug/submissions': typeof ApiPublicFormsSlugSubmissionsRoute
  '/api/public/forms/$slug/': typeof ApiPublicFormsSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/$'
    | '/admin/builder'
    | '/api/health'
    | '/api/settings'
    | '/admin/'
    | '/api/$resource/$id'
    | '/api/auth/$'
    | '/api/builder/commit'
    | '/api/builder/file'
    | '/api/cloudflare/apply'
    | '/api/cloudflare/authorize'
    | '/api/cloudflare/callback'
    | '/api/f/$slug'
    | '/api/github/authorize'
    | '/api/github/callback'
    | '/api/github/site'
    | '/api/github/status'
    | '/api/internal/provision'
    | '/api/settings/verify'
    | '/api/$resource/'
    | '/api/static/'
    | '/api/static/$collection/$id'
    | '/api/static/$collection/'
    | '/api/public/forms/$slug/submissions'
    | '/api/public/forms/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/$'
    | '/admin/builder'
    | '/api/health'
    | '/api/settings'
    | '/admin'
    | '/api/$resource/$id'
    | '/api/auth/$'
    | '/api/builder/commit'
    | '/api/builder/file'
    | '/api/cloudflare/apply'
    | '/api/cloudflare/authorize'
    | '/api/cloudflare/callback'
    | '/api/f/$slug'
    | '/api/github/authorize'
    | '/api/github/callback'
    | '/api/github/site'
    | '/api/github/status'
    | '/api/internal/provision'
    | '/api/settings/verify'
    | '/api/$resource'
    | '/api/static'
    | '/api/static/$collection/$id'
    | '/api/static/$collection'
    | '/api/public/forms/$slug/submissions'
    | '/api/public/forms/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin/$'
    | '/admin/builder'
    | '/api/health'
    | '/api/settings'
    | '/admin/'
    | '/api/$resource/$id'
    | '/api/auth/$'
    | '/api/builder/commit'
    | '/api/builder/file'
    | '/api/cloudflare/apply'
    | '/api/cloudflare/authorize'
    | '/api/cloudflare/callback'
    | '/api/f/$slug'
    | '/api/github/authorize'
    | '/api/github/callback'
    | '/api/github/site'
    | '/api/github/status'
    | '/api/internal/provision'
    | '/api/settings/verify'
    | '/api/$resource/'
    | '/api/static/'
    | '/api/static/$collection/$id'
    | '/api/static/$collection/'
    | '/api/public/forms/$slug/submissions'
    | '/api/public/forms/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminSplatRoute: typeof AdminSplatRoute
  AdminBuilderRoute: typeof AdminBuilderRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiSettingsRoute: typeof ApiSettingsRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  ApiResourceIdRoute: typeof ApiResourceIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiBuilderCommitRoute: typeof ApiBuilderCommitRoute
  ApiBuilderFileRoute: typeof ApiBuilderFileRoute
  ApiCloudflareApplyRoute: typeof ApiCloudflareApplyRoute
  ApiCloudflareAuthorizeRoute: typeof ApiCloudflareAuthorizeRoute
  ApiCloudflareCallbackRoute: typeof ApiCloudflareCallbackRoute
  ApiFSlugRoute: typeof ApiFSlugRoute
  ApiGithubAuthorizeRoute: typeof ApiGithubAuthorizeRoute
  ApiGithubCallbackRoute: typeof ApiGithubCallbackRoute
  ApiGithubSiteRoute: typeof ApiGithubSiteRoute
  ApiGithubStatusRoute: typeof ApiGithubStatusRoute
  ApiInternalProvisionRoute: typeof ApiInternalProvisionRoute
  ApiResourceIndexRoute: typeof ApiResourceIndexRoute
  ApiStaticIndexRoute: typeof ApiStaticIndexRoute
  ApiStaticCollectionIdRoute: typeof ApiStaticCollectionIdRoute
  ApiStaticCollectionIndexRoute: typeof ApiStaticCollectionIndexRoute
  ApiPublicFormsSlugSubmissionsRoute: typeof ApiPublicFormsSlugSubmissionsRoute
  ApiPublicFormsSlugIndexRoute: typeof ApiPublicFormsSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$': {
      id: '/admin/$'
      path: '/admin/$'
      fullPath: '/admin/$'
      preLoaderRoute: typeof AdminSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/builder': {
      id: '/admin/builder'
      path: '/admin/builder'
      fullPath: '/admin/builder'
      preLoaderRoute: typeof AdminBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/settings': {
      id: '/api/settings'
      path: '/api/settings'
      fullPath: '/api/settings'
      preLoaderRoute: typeof ApiSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$resource/': {
      id: '/api/$resource/'
      path: '/api/$resource'
      fullPath: '/api/$resource/'
      preLoaderRoute: typeof ApiResourceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$resource/$id': {
      id: '/api/$resource/$id'
      path: '/api/$resource/$id'
      fullPath: '/api/$resource/$id'
      preLoaderRoute: typeof ApiResourceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/builder/commit': {
      id: '/api/builder/commit'
      path: '/api/builder/commit'
      fullPath: '/api/builder/commit'
      preLoaderRoute: typeof ApiBuilderCommitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/builder/file': {
      id: '/api/builder/file'
      path: '/api/builder/file'
      fullPath: '/api/builder/file'
      preLoaderRoute: typeof ApiBuilderFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cloudflare/apply': {
      id: '/api/cloudflare/apply'
      path: '/api/cloudflare/apply'
      fullPath: '/api/cloudflare/apply'
      preLoaderRoute: typeof ApiCloudflareApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cloudflare/authorize': {
      id: '/api/cloudflare/authorize'
      path: '/api/cloudflare/authorize'
      fullPath: '/api/cloudflare/authorize'
      preLoaderRoute: typeof ApiCloudflareAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cloudflare/callback': {
      id: '/api/cloudflare/callback'
      path: '/api/cloudflare/callback'
      fullPath: '/api/cloudflare/callback'
      preLoaderRoute: typeof ApiCloudflareCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/f/$slug': {
      id: '/api/f/$slug'
      path: '/api/f/$slug'
      fullPath: '/api/f/$slug'
      preLoaderRoute: typeof ApiFSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/authorize': {
      id: '/api/github/authorize'
      path: '/api/github/authorize'
      fullPath: '/api/github/authorize'
      preLoaderRoute: typeof ApiGithubAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/callback': {
      id: '/api/github/callback'
      path: '/api/github/callback'
      fullPath: '/api/github/callback'
      preLoaderRoute: typeof ApiGithubCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/site': {
      id: '/api/github/site'
      path: '/api/github/site'
      fullPath: '/api/github/site'
      preLoaderRoute: typeof ApiGithubSiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/status': {
      id: '/api/github/status'
      path: '/api/github/status'
      fullPath: '/api/github/status'
      preLoaderRoute: typeof ApiGithubStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/provision': {
      id: '/api/internal/provision'
      path: '/api/internal/provision'
      fullPath: '/api/internal/provision'
      preLoaderRoute: typeof ApiInternalProvisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/settings/verify': {
      id: '/api/settings/verify'
      path: '/verify'
      fullPath: '/api/settings/verify'
      preLoaderRoute: typeof ApiSettingsVerifyRouteImport
      parentRoute: typeof ApiSettingsRoute
    }
    '/api/static/': {
      id: '/api/static/'
      path: '/api/static'
      fullPath: '/api/static/'
      preLoaderRoute: typeof ApiStaticIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/static/$collection/': {
      id: '/api/static/$collection/'
      path: '/api/static/$collection'
      fullPath: '/api/static/$collection/'
      preLoaderRoute: typeof ApiStaticCollectionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/static/$collection/$id': {
      id: '/api/static/$collection/$id'
      path: '/api/static/$collection/$id'
      fullPath: '/api/static/$collection/$id'
      preLoaderRoute: typeof ApiStaticCollectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/forms/$slug/': {
      id: '/api/public/forms/$slug/'
      path: '/api/public/forms/$slug'
      fullPath: '/api/public/forms/$slug/'
      preLoaderRoute: typeof ApiPublicFormsSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/forms/$slug/submissions': {
      id: '/api/public/forms/$slug/submissions'
      path: '/api/public/forms/$slug/submissions'
      fullPath: '/api/public/forms/$slug/submissions'
      preLoaderRoute: typeof ApiPublicFormsSlugSubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiSettingsRouteChildren {
  ApiSettingsVerifyRoute: typeof ApiSettingsVerifyRoute
}

const ApiSettingsRouteChildren: ApiSettingsRouteChildren = {
  ApiSettingsVerifyRoute: ApiSettingsVerifyRoute,
}

const ApiSettingsRouteWithChildren = ApiSettingsRoute._addFileChildren(
  ApiSettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminSplatRoute: AdminSplatRoute,
  AdminBuilderRoute: AdminBuilderRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiSettingsRoute: ApiSettingsRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  ApiResourceIdRoute: ApiResourceIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiBuilderCommitRoute: ApiBuilderCommitRoute,
  ApiBuilderFileRoute: ApiBuilderFileRoute,
  ApiCloudflareApplyRoute: ApiCloudflareApplyRoute,
  ApiCloudflareAuthorizeRoute: ApiCloudflareAuthorizeRoute,
  ApiCloudflareCallbackRoute: ApiCloudflareCallbackRoute,
  ApiFSlugRoute: ApiFSlugRoute,
  ApiGithubAuthorizeRoute: ApiGithubAuthorizeRoute,
  ApiGithubCallbackRoute: ApiGithubCallbackRoute,
  ApiGithubSiteRoute: ApiGithubSiteRoute,
  ApiGithubStatusRoute: ApiGithubStatusRoute,
  ApiInternalProvisionRoute: ApiInternalProvisionRoute,
  ApiResourceIndexRoute: ApiResourceIndexRoute,
  ApiStaticIndexRoute: ApiStaticIndexRoute,
  ApiStaticCollectionIdRoute: ApiStaticCollectionIdRoute,
  ApiStaticCollectionIndexRoute: ApiStaticCollectionIndexRoute,
  ApiPublicFormsSlugSubmissionsRoute: ApiPublicFormsSlugSubmissionsRoute,
  ApiPublicFormsSlugIndexRoute: ApiPublicFormsSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
